### ISSUE TITLE
typo, Cryptogtaphic keys in secrets document

### ISSUE THREAD

**Issue by wishwisdom** [corda/corda-docs#415]
I found mis-word(typo), which is 'Cryptogtaphic', on https://docs.corda.net/docs/corda-enterprise/4.7/secrets.html

Cryptogtaphic keys -> Cryptographic keys.

![스크린샷 2021-03-09 오후 2 47 14](https://user-images.githubusercontent.com/2561904/110424660-7a712180-80e6-11eb-83d1-5b5f16a199f7.png)

**Comment by ivanterziev-r3** [comment]
Hey @wishwisdom - thank you for reporting this, I'll fix it today.

**Comment by ivanterziev-r3** [comment]
For internal tracking: https://r3-cev.atlassian.net/browse/DOC-1810

**Comment by ivanterziev-r3** [comment]
PR https://github.com/corda/corda-docs/pull/416 - will be published later this morning.
